# Service Registry (Eureka Server)
spring.application.name=service-registry

server.port=${PORT:8761}

# Eureka Server
# Do not register itself.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable Spring Cloud auto service registration (prevents eurekaAutoServiceRegistration issues)
spring.cloud.service-registry.auto-registration.enabled=false

# Optional dev tuning
eureka.server.enable-self-preservation=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
